concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: concourse1@#$
    PGDATA: /database

concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: "${CONCOURSE_LOGIN}"
    CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_PASSWORD}"
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_POSTGRES_DATA_SOURCE: "postgres://concourse:concourse1@#$@concourse-db:5432/concourse?sslmode=disable"

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

gerrit:
  image: gerritforge/gerrit-ubuntu15.04
  links: [concourse-worker]
  ports: ["8090:8090", "29418:29418"]
  volumes: ["./gerrit/etc:/var/gerrit/etc"]
